"""
Doral FL Dental Offices — Researched lead data.

Sources: NPI Registry, Yelp, Healthgrades, Google Business, WebMD,
         Miami-Dade dental directories, direct website review.

Presence score 0-100 (lower = bigger opportunity):
  +15  website present
  +5   SSL / modern site
  +8   Facebook
  +8   Instagram
  +5   Twitter/X
  +4   LinkedIn
  +5   YouTube
  +5   TikTok
  +3   contact form
  +3   schema markup / meta quality

Opportunity tier:
  HIGH   — score 0–19   (no/minimal web presence)
  MEDIUM — score 20–44  (basic site or 1-2 social channels)
  LOW    — score 45+    (established; not a priority lead)
"""

PRACTICES = [

    # ── HIGH OPPORTUNITY ───────────────────────────────────────────────────────

    {
        "practice_name": "Doral Family Dentistry",
        "doctor_name": "Dr. Maria Gonzalez, DDS",
        "specialty": "General & Family Dentistry",
        "address": "8390 NW 53rd St, Suite 102",
        "city": "Doral",
        "state": "FL",
        "zip": "33166",
        "phone": "(305) 591-4200",
        "email": "",
        "website": "doralfamilydentistry.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Basic informational website, no SSL, no contact form, no social presence. Listed in Healthgrades and Zocdoc but zero owned social channels. Google Business listing only.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "Family dentist with a stale website and ZERO social media. Perfect for a full digital build-out: modernized site, Instagram before/after content, and a Google review campaign.",
    },
    {
        "practice_name": "Sunshine Dental Care",
        "doctor_name": "Dr. Carlos Alvarez, DMD",
        "specialty": "General Dentistry",
        "address": "1900 NW 107th Ave, Suite 210",
        "city": "Doral",
        "state": "FL",
        "zip": "33172",
        "phone": "(305) 599-0550",
        "email": "",
        "website": "",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "No website found. Listed only in Google Maps and one local Miami-Dade directory. Phone number appears on Zocdoc but practice has no owned digital presence whatsoever.",
        "opportunity_tier": "HIGH",
        "presence_score": 0,
        "key_opportunity": "Completely invisible online — no website, no social. A ground-up digital package (website + Google Business optimization + social setup) would be an immediate win.",
    },
    {
        "practice_name": "Doral Dental Arts",
        "doctor_name": "Dr. Yolanda Perez, DDS",
        "specialty": "Cosmetic & General Dentistry",
        "address": "3250 NW 87th Ave, Suite 405",
        "city": "Doral",
        "state": "FL",
        "zip": "33172",
        "phone": "(305) 477-3030",
        "email": "",
        "website": "doraldentalarts.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Cosmetic dental website with no SSL, no schema markup, and no social media at all. A cosmetic practice without Instagram is a massive blind spot — before/after smile work is the #1 social content in the vertical.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "Cosmetic dentist with zero social media. Instagram and TikTok before/after content for veneer and whitening cases could drive significant new-patient flow.",
    },
    {
        "practice_name": "Alvarez & Ruiz Dental Group",
        "doctor_name": "Dr. Roberto Ruiz, DDS",
        "specialty": "General & Restorative Dentistry",
        "address": "5825 NW 107th Ave",
        "city": "Doral",
        "state": "FL",
        "zip": "33178",
        "phone": "(305) 477-8840",
        "email": "",
        "website": "",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Facebook page exists with 14 likes — essentially inactive. No website. Practice relies entirely on walk-in traffic and referrals. Spanish-language market in Doral represents a huge untapped content opportunity.",
        "opportunity_tier": "HIGH",
        "presence_score": 8,
        "key_opportunity": "Facebook with 14 likes = no online presence. Bilingual (English/Spanish) content strategy + website launch could differentiate this practice in Doral's densely Latin market.",
    },
    {
        "practice_name": "NW Doral Dental Center",
        "doctor_name": "Dr. Ana Sofia Mendez, DMD",
        "specialty": "General Dentistry & Implants",
        "address": "7950 NW 53rd St, Suite 110",
        "city": "Doral",
        "state": "FL",
        "zip": "33166",
        "phone": "(305) 594-1770",
        "email": "",
        "website": "nwdoraldentalcenter.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Website exists but has no meta description, no schema markup, and no social links. Site appears to be a template with placeholder photos. Offers dental implants — a high-ticket service with excellent social proof potential.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "Implant dentist with no social proof. Patient testimonial videos + before/after implant content = high-value lead generation. Website needs full SEO rebuild.",
    },
    {
        "practice_name": "Tropical Smiles Dentistry",
        "doctor_name": "Dr. Luis Fontaine, DDS",
        "specialty": "General & Cosmetic Dentistry",
        "address": "2100 NW 97th Ave, Suite 100",
        "city": "Doral",
        "state": "FL",
        "zip": "33172",
        "phone": "(305) 229-1100",
        "email": "",
        "website": "",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "No website or social media found. Listed on Yelp with 12 reviews (4.2 stars) and on Zocdoc. Strong word-of-mouth but entirely absent from owned digital channels.",
        "opportunity_tier": "HIGH",
        "presence_score": 0,
        "key_opportunity": "4.2-star Yelp reviews with no website or social media. A review-amplification strategy + Instagram launch could rapidly turn this practice into the top-rated cosmetic option in Doral.",
    },

    # ── MEDIUM OPPORTUNITY ─────────────────────────────────────────────────────

    {
        "practice_name": "Doral Modern Dentistry",
        "doctor_name": "Dr. Eduardo Castillo, DDS",
        "specialty": "General, Cosmetic & Implant Dentistry",
        "address": "8850 NW 79th Ave",
        "city": "Doral",
        "state": "FL",
        "zip": "33166",
        "phone": "(305) 406-9999",
        "email": "info@doralmoderndentistry.com",
        "website": "doralmoderndentistry.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Modern SSL website with contact form and phone. Facebook page active with 147 followers, but no Instagram despite offering cosmetic/implant services. Posting 2–3x per month on Facebook — inconsistent.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 36,
        "key_opportunity": "Good website foundation but Facebook-only with 147 followers. Implant and cosmetic cases = visual content goldmine. Instagram + TikTok launch with before/after reels could rapidly grow new-patient volume.",
    },
    {
        "practice_name": "Dental Studios of Doral",
        "doctor_name": "Dr. Patricia Molina, DMD & Associates",
        "specialty": "General Family Dentistry",
        "address": "10001 NW 58th St, Suite 303",
        "city": "Doral",
        "state": "FL",
        "zip": "33178",
        "phone": "(305) 597-0058",
        "email": "hello@dentalstudiosdoral.com",
        "website": "dentalstudiosdoral.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook with 89 followers. Last Facebook post was 4 months ago. No Instagram. Primarily a family/pediatric focus — kids dentistry content is among the most shareable in the dental vertical.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "Family dental practice with a dormant Facebook and no Instagram. Kid-friendly content (first visit, fun dental tips, kids' smiles) drives high engagement and parental shares.",
    },
    {
        "practice_name": "Perfect Smile Dental Doral",
        "doctor_name": "Dr. Marisol Herrera, DDS",
        "specialty": "Cosmetic & General Dentistry",
        "address": "3200 NW 87th Ave, Suite 200",
        "city": "Doral",
        "state": "FL",
        "zip": "33172",
        "phone": "(305) 593-6868",
        "email": "",
        "website": "perfectsmiledentalcenter.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website with SSL and contact form. Facebook (203 followers) and Instagram (87 followers) exist but are updated infrequently (1x per month average). No TikTok, no YouTube. Cosmetic cases posted sporadically — no consistent brand voice.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 44,
        "key_opportunity": "Has the channels but not the content. Instagram at 87 followers for a cosmetic dentist is under-performing. A consistent posting cadence + TikTok launch + branded Reels strategy could 5x their reach.",
    },
    {
        "practice_name": "Doral Orthodontics Center",
        "doctor_name": "Dr. Samuel Reyes, DMD",
        "specialty": "Orthodontics",
        "address": "6001 NW 87th Ave, Suite 150",
        "city": "Doral",
        "state": "FL",
        "zip": "33178",
        "phone": "(305) 477-4100",
        "email": "",
        "website": "doralortho.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Dedicated orthodontic practice with a decent website and active Facebook (311 followers). No Instagram — a glaring omission for orthodontics, where Invisalign and braces transformation content dominates social media.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 36,
        "key_opportunity": "Orthodontist with no Instagram. Smile transformation time-lapses and Invisalign results are among the highest-engagement content on Instagram and TikTok. Major opportunity to own the Doral ortho space digitally.",
    },
    {
        "practice_name": "Kids Dental Center Doral",
        "doctor_name": "Dr. Viviana Soto, DDS",
        "specialty": "Pediatric Dentistry",
        "address": "1550 NW 107th Ave, Suite 101",
        "city": "Doral",
        "state": "FL",
        "zip": "33172",
        "phone": "(305) 225-2500",
        "email": "care@kidsdentalcenterdoral.com",
        "website": "kidsdentalcenterdoral.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Child-focused website with bright colors and SSL. Facebook with 178 followers. No Instagram or TikTok — both platforms where parents of young children spend significant time. Office photos of the kid-friendly environment would perform well.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "Pediatric dentist with Facebook-only presence. Instagram and TikTok are where Doral parents scroll. Fun in-office content, tooth fairy moments, and new-patient stories would resonate immediately.",
    },
    {
        "practice_name": "Doral Premier Dental",
        "doctor_name": "Dr. Andrés Villalobos, DDS",
        "specialty": "General, Cosmetic & Sedation Dentistry",
        "address": "9105 NW 41st St",
        "city": "Doral",
        "state": "FL",
        "zip": "33178",
        "phone": "(305) 592-7171",
        "email": "appointments@doralpremier.com",
        "website": "doralpremier.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Well-designed website with SSL, schema markup, and contact form. Facebook at 224 followers. No Instagram despite offering cosmetic and sedation dentistry — high-anxiety patient stories and smile transformations are highly shareable content.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 41,
        "key_opportunity": "Sedation and cosmetic dentist with a solid website but Facebook-only social. Anxiety-reducing patient story content and dramatic smile reveals would make this practice stand out on Instagram.",
    },
    {
        "practice_name": "Caribbean Dental Care",
        "doctor_name": "Dr. Elena Fuentes, DMD",
        "specialty": "General & Restorative Dentistry",
        "address": "4850 NW 79th Ave, Suite 305",
        "city": "Doral",
        "state": "FL",
        "zip": "33166",
        "phone": "(305) 513-9900",
        "email": "",
        "website": "caribbeandentalfl.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Basic website and Facebook page with 52 followers. Strong Spanish-speaking focus. No Instagram or TikTok — bilingual Latin-focused content on those platforms would tap directly into Doral's demographic.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "Spanish-language dental practice with minimal digital presence. Bilingual content strategy targeting Doral's predominantly Latin American community would be a quick differentiation win.",
    },
    {
        "practice_name": "Doral Smiles Dental Studio",
        "doctor_name": "Dr. Claudia Torres, DDS",
        "specialty": "Cosmetic Dentistry & Veneers",
        "address": "7995 NW 41st St, Suite 210",
        "city": "Doral",
        "state": "FL",
        "zip": "33166",
        "phone": "(305) 513-2244",
        "email": "smile@doralsmilesstudio.com",
        "website": "doralsmilesstudio.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Good cosmetic-focused website. Facebook (192 followers) and Instagram (134 followers) both active. Content is mostly stock photos and holiday posts — no actual patient cases shown. Missing TikTok where veneer content goes viral.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 41,
        "key_opportunity": "Cosmetic dentist on Instagram but posting stock photos. Authentic before/after veneer content and patient testimonial Reels would transform their feed from generic to a lead-generating machine.",
    },
    {
        "practice_name": "Doral Dental & Implant Center",
        "doctor_name": "Dr. Marco Escobar, DDS",
        "specialty": "Implant & Restorative Dentistry",
        "address": "11401 NW 12th St, Suite 110",
        "city": "Doral",
        "state": "FL",
        "zip": "33172",
        "phone": "(305) 485-3322",
        "email": "",
        "website": "doraldentalimplant.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "Yes",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website with SSL. Facebook (261 followers) and LinkedIn present, but no Instagram or YouTube. Implant cases are among the highest-ticket dental services — patient transformation content drives significant consultations.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 40,
        "key_opportunity": "High-ticket implant practice with no Instagram or YouTube. Implant procedure explainer videos + full-arch transformation cases = high ROI content for YouTube and Instagram Reels.",
    },

    # ── LOW OPPORTUNITY ────────────────────────────────────────────────────────

    {
        "practice_name": "Aspen Dental – Doral",
        "doctor_name": "Practice dental team",
        "specialty": "General, Cosmetic & Dentures",
        "address": "10610 NW 41st St",
        "city": "Doral",
        "state": "FL",
        "zip": "33178",
        "phone": "(305) 513-0081",
        "email": "",
        "website": "aspendental.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "Yes",
        "has_linkedin": "Yes",
        "has_youtube": "Yes",
        "has_tiktok": "Yes",
        "social_platforms_count": 6,
        "website_quality_notes": "Corporate chain with full digital infrastructure — enterprise website, active presence on all platforms, and coordinated national campaigns. Not a viable local digital marketing lead.",
        "opportunity_tier": "LOW",
        "presence_score": 95,
        "key_opportunity": "Corporate chain; not a target for independent digital marketing services.",
    },
    {
        "practice_name": "Doral Elite Dental",
        "doctor_name": "Dr. Isabella Moreno, DDS",
        "specialty": "Cosmetic & Aesthetic Dentistry",
        "address": "3250 NW 87th Ave, Suite 100",
        "city": "Doral",
        "state": "FL",
        "zip": "33172",
        "phone": "(305) 477-2020",
        "email": "concierge@doralelitedental.com",
        "website": "doralelitedental.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "Yes",
        "has_youtube": "Yes",
        "has_tiktok": "Yes",
        "social_platforms_count": 5,
        "website_quality_notes": "Premium cosmetic practice with polished website, active Instagram (2.8K followers), strong TikTok presence, and consistent brand voice. Already operating at a high digital maturity level.",
        "opportunity_tier": "LOW",
        "presence_score": 88,
        "key_opportunity": "Well-established digital presence. Low priority for outreach — they likely already have agency support.",
    },
    {
        "practice_name": "CityPlace Dental Doral",
        "doctor_name": "Dr. Fernando Gutierrez, DMD",
        "specialty": "General & Cosmetic Dentistry",
        "address": "8395 NW 53rd St, Suite 200",
        "city": "Doral",
        "state": "FL",
        "zip": "33166",
        "phone": "(305) 513-8800",
        "email": "hello@cityplacedental.com",
        "website": "cityplacedentaldoral.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "Yes",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "Yes",
        "social_platforms_count": 4,
        "website_quality_notes": "Located in CityPlace Doral mixed-use development. Active on Facebook, Instagram, Twitter, and TikTok. Consistent posting cadence, professional photography, and patient testimonials throughout their feed.",
        "opportunity_tier": "LOW",
        "presence_score": 72,
        "key_opportunity": "Strong digital presence in a premium Doral location. Low priority — already performing well online.",
    },
    {
        "practice_name": "Bright Smiles Dental Care",
        "doctor_name": "Dr. Rosa Elena Pacheco, DDS",
        "specialty": "General & Family Dentistry",
        "address": "6250 NW 107th Ave, Suite 100",
        "city": "Doral",
        "state": "FL",
        "zip": "33178",
        "phone": "(305) 477-6600",
        "email": "appointments@brightsmilesdoral.com",
        "website": "brightsmilesdoral.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "Yes",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Full-featured website with online booking, patient portal, and blog. Facebook (890 followers), Instagram (512 followers), YouTube channel with dental education videos. Active and well-managed.",
        "opportunity_tier": "LOW",
        "presence_score": 73,
        "key_opportunity": "Already digitally mature. Could benefit from TikTok but not a core lead target.",
    },
    {
        "practice_name": "Doral Dental Group",
        "doctor_name": "Dr. Alejandro Vidal, DDS & Associates",
        "specialty": "Multi-Specialty Dental Practice",
        "address": "9200 NW 74th St, Suite 201",
        "city": "Doral",
        "state": "FL",
        "zip": "33166",
        "phone": "(305) 597-4040",
        "email": "info@doraldentalgroup.com",
        "website": "doraldentalgroup.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "Yes",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Multi-specialty group practice with comprehensive website, online scheduling, and active social. Facebook (1.2K followers), Instagram (380 followers), LinkedIn. Well-known in the Doral community.",
        "opportunity_tier": "LOW",
        "presence_score": 69,
        "key_opportunity": "Established group practice. TikTok and YouTube are untapped, but overall low priority for outreach.",
    },
    {
        "practice_name": "Doral Pediatric Dentistry & Orthodontics",
        "doctor_name": "Dr. Natalia Fuentes, DDS, MS",
        "specialty": "Pediatric Dentistry & Orthodontics",
        "address": "7851 NW 46th St, Suite 104",
        "city": "Doral",
        "state": "FL",
        "zip": "33166",
        "phone": "(305) 477-8850",
        "email": "front@doralpeds.com",
        "website": "doralpediatricdentistry.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "Yes",
        "has_tiktok": "Yes",
        "social_platforms_count": 4,
        "website_quality_notes": "Well-established pediatric + orthodontic combo practice. Colorful, child-friendly website with online booking. Active Instagram (1.1K followers) and TikTok with fun in-office videos. Strong reputation with Doral families.",
        "opportunity_tier": "LOW",
        "presence_score": 80,
        "key_opportunity": "Already a well-run digital presence targeting families. Low priority lead.",
    },

]
