"""
Generate Naples FL Doctors - Low Online Presence CSV from researched data.
"""

import csv

PRACTICES = [
    # ── HIGH OPPORTUNITY ──────────────────────────────────────────
    {
        "practice_name": "Kathleen Broderick, MD",
        "doctor_name": "Dr. Kathleen Broderick, MD",
        "specialty": "Internal Medicine",
        "address": "700 2nd Ave N, Suite 204",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 263-2200",
        "email": "kathleenbroderick@yahoo.com",
        "website": "",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "NO WEBSITE — found only on 3rd-party directories (Healthgrades, WebMD, Vitals, Doximity). Email is a personal Yahoo address.",
        "opportunity_tier": "HIGH",
        "presence_score": 0,
        "key_opportunity": "No website, no social media whatsoever. Solo internist with 41 years in Naples. Bilingual English/Spanish. Huge build-from-scratch opportunity.",
    },
    {
        "practice_name": "Naples Family Practice",
        "doctor_name": "Dr. Gerald Levens, MD",
        "specialty": "Family Medicine / Concierge",
        "address": "1175 Creekside Pkwy",
        "city": "Naples",
        "state": "FL",
        "zip": "34108",
        "phone": "(239) 284-4333",
        "email": "geraldlevensmd@gmail.com",
        "website": "naplesfamilypractice.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Basic dated website. No social media links. Personal Gmail for business contact — signals low digital sophistication.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "No social media on any platform. Basic old website. Under-300-patient membership practice since 2007. Low-hanging fruit.",
    },
    {
        "practice_name": "Dr. Anthony D'Agostino, MD",
        "doctor_name": "Dr. Anthony M. D'Agostino, MD, FACP",
        "specialty": "Internal Medicine / Primary Care",
        "address": "1350 9th St N, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 262-6111",
        "email": "office@adagostino.com",
        "website": "adagostino.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Minimal basic website. No social media integration anywhere. Solo practice with 2,500+ patients but zero social presence.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "Solo internist since 1996 with 2,500+ patients and zero social media. Strong patient base with no digital marketing.",
    },
    {
        "practice_name": "Integris Physicians (Endocrinology & Allergy)",
        "doctor_name": "Dr. Valeriu Neagu, MD & Dr. Florina Neagu, MD",
        "specialty": "Endocrinology / Allergy & Immunology",
        "address": "1019 Crosspointe Dr, Suite 1",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 799-6950",
        "email": "contact@integrisdoc.com",
        "website": "integrisdoc.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Basic informational website only. No social media on any platform.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "2-physician specialty practice with no social presence. Endocrinology and allergy are high-demand specialties with visual content potential.",
    },
    {
        "practice_name": "Psychiatry of Naples",
        "doctor_name": "Psychiatric Nurse Practitioner (women-owned)",
        "specialty": "Psychiatry / Mental Health",
        "address": "365 5th Ave S",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 298-1998",
        "email": "",
        "website": "psychnaples.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Basic website. Zero social media presence detected. Boutique women-owned practice offering private/in-home visits.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "Mental health is hugely popular on social media. Women-owned boutique psych practice with zero online presence = strong opportunity.",
    },
    {
        "practice_name": "Naples Independent Physicians",
        "doctor_name": "Dr. Jennifer Foley, MD & Dr. Louis Foley, MD",
        "specialty": "Pediatrics / Women's Health",
        "address": "1217 Piper Blvd, Suite 202",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 920-9010",
        "email": "",
        "website": "naplesindependentphysicians.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Membership practice website; no social media links found anywhere. Office hours Mon–Thu 8:30am–5pm.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "Pediatrics + women's health with ZERO social media. Parents and women are highly active on Instagram/Facebook. Prime audience.",
    },
    {
        "practice_name": "Southwest Florida Women's Group",
        "doctor_name": "All-woman physician team (multiple MDs)",
        "specialty": "OB/GYN",
        "address": "1890 SW Health Pkwy, Suite 303",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 593-0990",
        "email": "",
        "website": "obgynnaplesflorida.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Website present. No dedicated social media accounts found. Only a Nextdoor presence. In practice since 2001.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "All-female OBGYN group with zero social media since 2001. Women's health content crushes on Instagram/Reels. Huge gap.",
    },
    {
        "practice_name": "Diamond Cove Concierge Medicine",
        "doctor_name": "Dr. Michelle Becker, MD",
        "specialty": "Concierge Primary Care",
        "address": "1890 SW Health Pkwy, Suite 100",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 207-8844",
        "email": "",
        "website": "diamondcovemd.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Solid website but zero social media presence. Relies on Yelp (21 reviews) and Birdeye. $5,700/yr membership, 150 patient cap.",
        "opportunity_tier": "HIGH",
        "presence_score": 18,
        "key_opportunity": "High-end concierge practice ($5,700/yr) with no social media. Wealthy Naples clientele. Perfect for lifestyle/wellness content.",
    },
    {
        "practice_name": "Seaside Oaks Psychiatry",
        "doctor_name": "Dr. Monica Robles, MD",
        "specialty": "Psychiatry / Ketamine / TMS",
        "address": "1045 Crosspointe Dr, Suite 2",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 784-2297",
        "email": "",
        "website": "seasideoakspsychiatry.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "Yes",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Good website with services listed. LinkedIn only (no public-facing social). No Facebook or Instagram.",
        "opportunity_tier": "HIGH",
        "presence_score": 19,
        "key_opportunity": "Ketamine + TMS therapy practice with LinkedIn only. Mental health social content explodes on IG/TikTok. Major growth opportunity.",
    },

    # ── MEDIUM OPPORTUNITY ────────────────────────────────────────
    {
        "practice_name": "Internal Medicine Partners (IMP Naples)",
        "doctor_name": "Dr. Ralph Rodriguez, MD & Dr. Alejandro Blanco, MD",
        "specialty": "Internal Medicine / Aesthetics / Wellness",
        "address": "1726 Medical Blvd, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 596-8804",
        "email": "",
        "website": "impnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Professional website with aesthetics/wellness section. Facebook page only — no Instagram despite offering aesthetic services (prime IG content).",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "Aesthetics + internal medicine with Facebook only. Aesthetic procedures = Instagram gold. Missing Instagram is a big gap.",
    },
    {
        "practice_name": "Well-Being Medical Center",
        "doctor_name": "Dr. Ricardo Martinez, MD",
        "specialty": "Internal Medicine / Urgent Care",
        "address": "851 5th Ave N, Suite 102",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 315-7801",
        "email": "",
        "website": "well-beingmedicalcenter.org",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook only. 98% recommendation rating from patients, 56 reviews. Strong reputation, weak digital marketing.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "98% recommendation rate but only Facebook. Could easily convert great reviews into Instagram/Google presence.",
    },
    {
        "practice_name": "Concierge Medical of Naples",
        "doctor_name": "Dr. Obayedur Khan, MD, FACP",
        "specialty": "Geriatrics / Internal Medicine / Concierge",
        "address": "599 Tamiami Trail N, Suite 204",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 304-8902",
        "email": "",
        "website": "conciergemedicalofnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Has a website and Facebook. No Instagram. Fellowship-trained geriatrician serving Naples since 2005, concierge model since 2015.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "Concierge geriatrics with Facebook only. Geriatric/senior health content is underserved on social. Good upgrade potential.",
    },
    {
        "practice_name": "Physicians Life Centers, LLC",
        "doctor_name": "Practice physicians",
        "specialty": "Internal Medicine / Holistic / Concierge",
        "address": "1048 Goodlette Rd N, Suite 101",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 325-6504",
        "email": "",
        "website": "physicianslifecenters.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook. Mind-body-spirit focus. No Instagram despite holistic/wellness approach which performs well on IG.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "Holistic concierge model with Facebook only. Wellness content thrives on Instagram and YouTube. Strong upgrade potential.",
    },
    {
        "practice_name": "Dr. Socrates Perez, MD",
        "doctor_name": "Dr. Socrates Perez-Rodriguez, MD",
        "specialty": "Internal Medicine / Primary Care",
        "address": "870 111th Ave N, Suite 3",
        "city": "Naples",
        "state": "FL",
        "zip": "34108",
        "phone": "(239) 331-5114",
        "email": "drsocratesperez@gmail.com",
        "website": "socratesperezmd.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website and Facebook. Personal Gmail for contact. No Instagram. 25+ years experience, accepting new patients.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "25+ year veteran with personal Gmail and Facebook only. Easy to upgrade website and expand social reach.",
    },
    {
        "practice_name": "North Naples Gynecology & Obstetrics",
        "doctor_name": "Dr. Dean B. Hildahl, MD",
        "specialty": "OB/GYN",
        "address": "1865 Veterans Park Dr, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 206-2780",
        "email": "",
        "website": "northnaplesobgyn.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + limited Facebook (low following/activity). No Instagram. OB/GYN is a top-performing content niche on social.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "OB/GYN with almost no social presence. Women's health content drives huge engagement on Instagram/Reels.",
    },
    {
        "practice_name": "Wellness for Women of Naples",
        "doctor_name": "Dr. Tracye Zlobl, MD",
        "specialty": "Gynecology / Menopause Management",
        "address": "6610 Willow Park Dr, Suite 102",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 262-3100",
        "email": "",
        "website": "wellnessforwomenofnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook. Menopause/hormone specialist. No Instagram despite menopause content booming on social.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "Menopause specialist with Facebook only. #menopause content explodes on Instagram/TikTok. Massive untapped audience.",
    },
    {
        "practice_name": "Meliora Healthcare",
        "doctor_name": "Multi-physician gastroenterology/pulmonology team",
        "specialty": "Gastroenterology / Hepatology / Sleep / Pulmonology",
        "address": "708 Goodlette-Frank Rd, 2nd Floor",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 291-7005",
        "email": "contact@meliorahealthcare.org",
        "website": "meliorahealthcare.com",
        "has_facebook": "No",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Instagram (@meliorahealth) with only 88 followers and 271 posts. Very low engagement despite content posting.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 28,
        "key_opportunity": "Posts content but only 88 followers. Needs strategy overhaul. No Facebook at all. Multi-specialty = diverse content angles.",
    },
    {
        "practice_name": "South Florida Internal Medicine",
        "doctor_name": "Dr. John Canterbury, MD",
        "specialty": "Internal Medicine / Primary Care",
        "address": "680 2nd Ave N, Suite 203",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 330-1382",
        "email": "",
        "website": "sflinternalmedicine.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook only. ABIM-certified. Employement physicals, preventive care, diabetes, hypertension. No Instagram.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "Established IM practice with Facebook only. Website is basic (http, not https). Full digital revamp opportunity.",
    },
    {
        "practice_name": "EPN Urgent Care",
        "doctor_name": "Physician-led urgent care group",
        "specialty": "Urgent Care / Occupational Medicine",
        "address": "6400 Davis Blvd, Suite 101",
        "city": "Naples",
        "state": "FL",
        "zip": "34104",
        "phone": "(239) 775-2300",
        "email": "",
        "website": "epncare.com",
        "has_facebook": "No",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Instagram with ONLY 7 followers and 10 posts — effectively zero. No Facebook. Operating since 2004.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 20,
        "key_opportunity": "20+ year urgent care with 7 Instagram followers. Essentially no social media. Strong base, zero online presence.",
    },
    {
        "practice_name": "VAVA Clinic",
        "doctor_name": "Dr. Vava Nyanudor, MD & Dr. Suzanna Boka, MD",
        "specialty": "Primary Care / Urgent Care",
        "address": "8855 Immokalee Rd, Unit 3",
        "city": "Naples",
        "state": "FL",
        "zip": "34120",
        "phone": "(239) 331-8520",
        "email": "",
        "website": "vavaclinic.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook with only 52 likes. 20+ years in Naples community. Minimal engagement. No Instagram.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "20+ years of community healthcare with only 52 Facebook likes. Very low visibility. Easy quick-win opportunity.",
    },
    {
        "practice_name": "First Care Clinic Naples",
        "doctor_name": "Veteran-owned physician group",
        "specialty": "Primary Care / Urgent Care",
        "address": "1201 Piper Blvd, Suite 24",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 260-5307",
        "email": "",
        "website": "firstcarenaples.com",
        "has_facebook": "No",
        "has_instagram": "Yes",
        "has_twitter": "Yes",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Instagram + Twitter — but very minimal activity. No Facebook. Veteran-owned since 2012.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 36,
        "key_opportunity": "Veteran-owned, has social handles but no real presence. Compelling brand story (veteran healthcare) underutilized.",
    },
    {
        "practice_name": "Collier Urgent Care Centers",
        "doctor_name": "Multi-physician urgent care group",
        "specialty": "Urgent Care (3 Naples locations)",
        "address": "1514 Immokalee Rd (+ 2 other locations)",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 593-3232",
        "email": "Info2@collierurgentcare.com",
        "website": "collierurgentcare.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Multi-location website + Facebook only. 3 Naples locations. 'Most Trusted' claim but minimal social. No Instagram.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "key_opportunity": "3-location urgent care with Facebook only. Large geographic reach in Naples with low social investment. Good ROI potential.",
    },

    # ── LOW OPPORTUNITY (well-established) ───────────────────────
    {
        "practice_name": "Prime MD of Naples",
        "doctor_name": "Practice physician group",
        "specialty": "Family Medicine / Geriatrics / Women's Health",
        "address": "Naples, FL 34110",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 481-4111",
        "email": "",
        "website": "primemdofnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active website + Facebook + Instagram (@primemdofnaples). Regularly updated. Lee Health affiliate.",
        "opportunity_tier": "LOW",
        "presence_score": 56,
        "key_opportunity": "Already active on Facebook and Instagram. Lower priority unless looking to expand into YouTube/TikTok.",
    },
    {
        "practice_name": "Advance Medical of Naples",
        "doctor_name": "Dr. Greg Leach, MD (founder)",
        "specialty": "Family Medicine / Urgent / Occupational",
        "address": "720 Goodlette Rd N",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 206-2525",
        "email": "",
        "website": "advmednaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "Yes",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Established website + Facebook (1,162 likes) + Twitter + Instagram. One of the most digitally active independent practices in Naples.",
        "opportunity_tier": "LOW",
        "presence_score": 66,
        "key_opportunity": "Well-established presence. Limited opportunity for new social media build. Could help with LinkedIn or YouTube/TikTok expansion.",
    },
    {
        "practice_name": "Dr. Lorna Fedelem, MD (Concierge Wellness)",
        "doctor_name": "Dr. Lorna J. Fedelem, MD",
        "specialty": "Family Medicine / Obesity Medicine / Concierge",
        "address": "9150 Galleria Ct, Suite 200",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 580-6390",
        "email": "",
        "website": "lornafedelemmd.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "Yes",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Modern website + Facebook + Instagram (@lornafedelemmd, 473 followers, 185 posts) + LinkedIn. Active multi-platform.",
        "opportunity_tier": "LOW",
        "presence_score": 61,
        "key_opportunity": "Active on multiple platforms. Lower priority. Could expand into TikTok/YouTube for obesity medicine content.",
    },
    {
        "practice_name": "Hobdari Family Health",
        "doctor_name": "Dr. Lindita R. Hobdari, MD",
        "specialty": "Family Medicine (Pediatric–Geriatric)",
        "address": "1855 Veterans Park Dr, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 260-1033",
        "email": "",
        "website": "hobdarihealth.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "Yes",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Facebook (739 likes) + Instagram (@hobdarihealth, 313 followers, 497 posts) + Twitter. Active. America's Most Honored Doctors.",
        "opportunity_tier": "LOW",
        "presence_score": 61,
        "key_opportunity": "Solid multi-platform presence. Lower priority. Twitter joined 2020 but no posts — that's a gap.",
    },
    {
        "practice_name": "Goodwin Medical Center",
        "doctor_name": "Dr. Nancy J. Goodwin, MD",
        "specialty": "Concierge / Aesthetic / Anti-Aging Medicine",
        "address": "12260 Tamiami Trail E, Unit 102",
        "city": "Naples",
        "state": "FL",
        "zip": "34113",
        "phone": "(239) 692-9096",
        "email": "",
        "website": "goodwinmedcenter.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook + Instagram (@goodwinmedcenter, 332 followers). Founded 2018. Double board-certified.",
        "opportunity_tier": "LOW",
        "presence_score": 51,
        "key_opportunity": "Active but 332 Instagram followers is still low. Anti-aging/aesthetic content has massive potential. Growth coaching opportunity.",
    },
    {
        "practice_name": "Dr. Diane Brzezinski, DO",
        "doctor_name": "Dr. Diane J. Brzezinski, DO, FACOI",
        "specialty": "Internal Medicine / Osteopathic",
        "address": "1250 Pine Ridge Rd, Suite 101A",
        "city": "Naples",
        "state": "FL",
        "zip": "34108",
        "phone": "(239) 261-9990",
        "email": "Denise@drbnaples.com",
        "website": "drbnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook (@DrBNaples) with 3,899 likes — strong Facebook presence. No Instagram despite popularity.",
        "opportunity_tier": "LOW",
        "presence_score": 53,
        "key_opportunity": "Strong Facebook (3,899 likes) but no Instagram. 9-time Best Physician winner. Perfect for Instagram expansion.",
    },
    {
        "practice_name": "Patel Health (Direct Primary Care)",
        "doctor_name": "Physician-owned DPC practice",
        "specialty": "Family Medicine / Direct Primary Care",
        "address": "Naples, FL",
        "city": "Naples",
        "state": "FL",
        "zip": "",
        "phone": "(702) 907-2835",
        "email": "info@patel.health",
        "website": "patel.health",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "DPC model with Facebook only. Wholesale meds/labs model. No Instagram.",
        "opportunity_tier": "LOW",
        "presence_score": 43,
        "key_opportunity": "Facebook only but borderline. DPC model resonates well on social. Instagram would help patient acquisition.",
    },
    {
        "practice_name": "Dr. Svetlana Kogan, MD (Custom Longevity)",
        "doctor_name": "Dr. Svetlana Kogan, MD, IFMCP",
        "specialty": "Functional / Integrative / Holistic Medicine",
        "address": "720 Fifth Ave S, Suite 209",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 676-6883",
        "email": "",
        "website": "customlongevity.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "Yes",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook + LinkedIn. IFM Certified. Functional medicine = very popular on Instagram/TikTok. Missing that channel.",
        "opportunity_tier": "LOW",
        "presence_score": 52,
        "key_opportunity": "Holistic/functional medicine with no Instagram. This niche DOMINATES social. Good upgrade opportunity.",
    },
    {
        "practice_name": "Women's Healthcare Physicians of Naples",
        "doctor_name": "Multiple board-certified OB/GYN physicians",
        "specialty": "OB/GYN",
        "address": "775 1st Ave N",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 217-6513",
        "email": "",
        "website": "whpnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook (334 likes) + Instagram location page. 2 locations. Moderate presence.",
        "opportunity_tier": "LOW",
        "presence_score": 56,
        "key_opportunity": "Active but low follower count. OB/GYN content performs extremely well. Strategy + content upgrade opportunity.",
    },
    {
        "practice_name": "A Woman's Place (OB/GYN)",
        "doctor_name": "Dr. Jeffrey Heitmann, MD & team",
        "specialty": "OB/GYN / 3D Mammography",
        "address": "1660 Medical Blvd, Suite 300",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 513-0053",
        "email": "",
        "website": "awpnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "Yes",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Facebook (1,092 likes) + Instagram (@awomansplacenaples) + LinkedIn. Established since 1988. 3D mammograms, MonaLisa Touch.",
        "opportunity_tier": "LOW",
        "presence_score": 66,
        "key_opportunity": "Strong established presence. Lower priority. No TikTok/YouTube despite rich women's health content potential.",
    },
    {
        "practice_name": "Shoreline Physician Group",
        "doctor_name": "Dr. Carlos Portu, MD",
        "specialty": "Internal Medicine / Primary Care",
        "address": "950 Manatee Rd",
        "city": "Naples",
        "state": "FL",
        "zip": "34114",
        "phone": "(239) 235-7908",
        "email": "drcarlosportu@gmail.com",
        "website": "shorelinephysicians.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "Yes",
        "has_linkedin": "Yes",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 4,
        "website_quality_notes": "Full multi-platform: Facebook + Instagram (@dr_portu) + Twitter + LinkedIn. Most digitally active independent physician found.",
        "opportunity_tier": "LOW",
        "presence_score": 76,
        "key_opportunity": "Most digital presence of any independent practice found. Not a good target for social media services.",
    },
]


def generate_csv():
    output_file = "naples_doctors_low_presence.csv"
    fieldnames = [
        "opportunity_tier",
        "presence_score",
        "practice_name",
        "doctor_name",
        "specialty",
        "address",
        "city",
        "state",
        "zip",
        "phone",
        "email",
        "website",
        "social_platforms_count",
        "has_facebook",
        "has_instagram",
        "has_twitter",
        "has_linkedin",
        "has_youtube",
        "has_tiktok",
        "website_quality_notes",
        "key_opportunity",
    ]

    sorted_practices = sorted(
        PRACTICES,
        key=lambda x: (
            0 if x["opportunity_tier"] == "HIGH" else
            1 if x["opportunity_tier"] == "MEDIUM" else 2,
            x["presence_score"]
        )
    )

    with open(output_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for p in sorted_practices:
            writer.writerow({k: p[k] for k in fieldnames})

    print(f"Written: {output_file}")

    high = sum(1 for p in PRACTICES if p["opportunity_tier"] == "HIGH")
    med  = sum(1 for p in PRACTICES if p["opportunity_tier"] == "MEDIUM")
    low  = sum(1 for p in PRACTICES if p["opportunity_tier"] == "LOW")

    print(f"\nSummary:")
    print(f"  HIGH opportunity (no/minimal presence): {high}")
    print(f"  MEDIUM opportunity (Facebook-only or near-zero social): {med}")
    print(f"  LOW opportunity (well-established): {low}")
    print(f"  Total practices researched: {len(PRACTICES)}")

    print(f"\nHIGH OPPORTUNITY LEADS:")
    for p in sorted_practices:
        if p["opportunity_tier"] == "HIGH":
            print(f"  [{p['presence_score']:2d}] {p['practice_name']} — {p['phone']} — {p['email'] or 'no email found'}")


if __name__ == "__main__":
    generate_csv()
