"""
Generate Naples FL Dental Offices - Low Online Presence CSV from researched data.
"""

import csv

PRACTICES = [
    # ── HIGH OPPORTUNITY ──────────────────────────────────────────
    {
        "practice_name": "Davey Family Dentistry",
        "doctor_name": "Dr. Jeremy Davey, DDS",
        "specialty": "General & Family Dentistry",
        "address": "661 Goodlette Rd N, Suite 107",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 434-8886",
        "email": "",
        "website": "daveyfamilydentistry.com",
        "has_facebook": "No",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 0,
        "website_quality_notes": "Basic practice website. No social media presence found on any platform — no Facebook, no Instagram, nothing. Listed only in Healthgrades, WebMD, and Gulfshore Life directories.",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "key_opportunity": "Solo family dentist with a website but ZERO social media. Strong patient reviews exist but no owned digital presence to show for it. Full build-from-scratch opportunity.",
    },
    {
        "practice_name": "Naples Dental Professionals",
        "doctor_name": "Dr. Katia Consuegra, DDS",
        "specialty": "General & Cosmetic Dentistry",
        "address": "4522 Executive Dr, Suite 101",
        "city": "Naples",
        "state": "FL",
        "zip": "34119",
        "phone": "(239) 592-9200",
        "email": "",
        "website": "naples-dental.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook page with only 23 likes — effectively a dead account. No Instagram despite offering cosmetic dentistry, which is a highly visual specialty.",
        "opportunity_tier": "HIGH",
        "presence_score": 18,
        "key_opportunity": "Facebook with 23 likes = essentially no online presence. Cosmetic dental work is Instagram gold. Smile makeovers, whitening results, before/after posts are perfect content.",
    },

    # ── MEDIUM OPPORTUNITY ────────────────────────────────────────
    {
        "practice_name": "Dental Specialty Center of Naples",
        "doctor_name": "Practice dental team",
        "specialty": "General, Cosmetic & Specialty Dentistry",
        "address": "4955 Castello Dr",
        "city": "Naples",
        "state": "FL",
        "zip": "34103",
        "phone": "(239) 227-2479",
        "email": "",
        "website": "dentalspecialtyflorida.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook with only 71 followers. No Instagram despite offering cosmetic and specialty services. Very low visibility for a multi-specialty practice.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "Multi-specialty center with only 71 Facebook followers and no Instagram. Orthodontic/smile transformations = viral content. Huge gap to fill.",
    },
    {
        "practice_name": "Page Family Dental Group",
        "doctor_name": "Dr. Christopher Page, DDS & team",
        "specialty": "General Family Dentistry",
        "address": "4953 Castello Dr, Suite 100",
        "city": "Naples",
        "state": "FL",
        "zip": "34103",
        "phone": "(239) 263-2122",
        "email": "frontdesk@pagefdg.com",
        "website": "pagefamilydentalgroup.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook only. No Instagram. Family practice (pediatric through adult). Strong candidate for family and kids dentistry content on social.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "Family dental group with Facebook only — no Instagram. Family/kids dentistry content (first visits, tooth fairy, Halloween candy) crushes on social.",
    },
    {
        "practice_name": "BayView Dental Arts",
        "doctor_name": "Practice dental team",
        "specialty": "Cosmetic & Restorative Dentistry",
        "address": "1001 10th Ave S, Suite 218",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 434-5545",
        "email": "office@bayviewdentalarts.com",
        "website": "bayviewdentalarts.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook only. No Instagram despite being a cosmetic/restorative practice. Smile makeovers are the single best content type for dental Instagram.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "Cosmetic dentistry in Downtown Naples with Facebook only. Before/after smile transformations drive massive engagement. IG is an obvious missing channel.",
    },
    {
        "practice_name": "Naples Dental Care",
        "doctor_name": "Practice dental team",
        "specialty": "General Dentistry / Affordable Dentures & Implants",
        "address": "4325 Tamiami Trl N",
        "city": "Naples",
        "state": "FL",
        "zip": "34103",
        "phone": "(239) 234-5284",
        "email": "",
        "website": "dentistofnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook (1,559 likes) but no Instagram, YouTube, or any other platform. Single-channel strategy limiting growth potential.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "1,559 Facebook followers with no Instagram = untapped audience. Expanding to IG and Google Business would significantly multiply visibility.",
    },
    {
        "practice_name": "The Dentistry in Naples",
        "doctor_name": "Practice dental team",
        "specialty": "General, Cosmetic, Emergency & Sedation Dentistry",
        "address": "1001 Crosspointe Drive, Suite 2",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 566-2422",
        "email": "",
        "website": "thedentistrynaples.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook only. Sedation dentistry is a specialized niche where anxious patients research heavily online — yet no Instagram or YouTube presence.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "Sedation + emergency dental practice with Facebook only. Patient calming videos and sedation explainers perform very well on YouTube/Instagram.",
    },
    {
        "practice_name": "Naples Smiles Dentistry",
        "doctor_name": "Practice dental team",
        "specialty": "General & Family Dentistry",
        "address": "5072 Airport Rd N",
        "city": "Naples",
        "state": "FL",
        "zip": "34105",
        "phone": "(239) 280-3646",
        "email": "",
        "website": "naplessmilesdentistry.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook. No Instagram despite 'Smiles' branding — a visually oriented name with no visual social media strategy.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "A 'Smiles' practice with no Instagram. Smile makeovers, whitening results, and patient testimonials on IG/Reels would immediately align with the brand.",
    },
    {
        "practice_name": "Naples Bay Dental Group",
        "doctor_name": "Practice dental team",
        "specialty": "General & Family Dentistry",
        "address": "5040 Tamiami Trl E, Suite 300",
        "city": "Naples",
        "state": "FL",
        "zip": "34113",
        "phone": "(239) 799-7244",
        "email": "",
        "website": "naplesbaydentalgroup.com",
        "has_facebook": "Yes",
        "has_instagram": "No",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 1,
        "website_quality_notes": "Website + Facebook only. South Naples family group with no Instagram or video content strategy to engage the local community.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "key_opportunity": "South Naples family dental group with Facebook only. Prime candidate for Instagram setup and Google Business optimization to capture local traffic.",
    },
    {
        "practice_name": "Naples Premier Dentistry",
        "doctor_name": "Practice dental team",
        "specialty": "General & Cosmetic Dentistry",
        "address": "12840 Tamiami Trl N, Suite 100",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 591-1000",
        "email": "naplespremier@mydentalmail.com",
        "website": "naplespremierdentistry.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook + Instagram (@naplespremierdentistry) — but Instagram has only 39 followers and 5 total posts. Effectively abandoned and dormant.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 25,
        "key_opportunity": "Has accounts set up but Instagram is essentially abandoned (39 followers, 5 posts). Needs content strategy and consistent posting to activate existing channels.",
    },
    {
        "practice_name": "Dental Care at Naples Lakes",
        "doctor_name": "Practice dental team",
        "specialty": "General & Family Dentistry",
        "address": "8615 Collier Blvd",
        "city": "Naples",
        "state": "FL",
        "zip": "34114",
        "phone": "(239) 544-4240",
        "email": "",
        "website": "dentalcareatnapleslakes.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook (152 likes) + Instagram (165 followers). Both accounts are active but very low engagement for the size of the surrounding community.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 31,
        "key_opportunity": "On two platforms but with very low engagement. Needs content strategy, posting schedule, and local community targeting to build real traction.",
    },
    {
        "practice_name": "Torrens Dental Care",
        "doctor_name": "Dr. Walfred Torrens, DMD",
        "specialty": "General Dentistry / Endodontics",
        "address": "1890 SW Health Pkwy, Suite 302",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 254-7727",
        "email": "info@torrensdental.com",
        "website": "torrensdental.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook + Instagram (@torrens_dentalcare, 76 followers, 246 posts). Posts regularly but gets almost no traction — content without strategy.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 31,
        "key_opportunity": "246 Instagram posts but only 76 followers — high effort, zero return. 20+ years experience is a powerful brand story being wasted without strategy.",
    },
    {
        "practice_name": "Cardinale Dentistry",
        "doctor_name": "Dr. Vincent Cardinale, DDS",
        "specialty": "General & Cosmetic Dentistry",
        "address": "1019 Crosspointe Dr, Suite 2",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 596-9868",
        "email": "",
        "website": "cardinaledentistry.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook (239 likes) + Instagram (@cardinaledentistry, 141 followers, 307 posts). 679 Healthgrades reviews signal strong patient base but low online visibility.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 31,
        "key_opportunity": "679 Healthgrades reviews but only 141 IG followers — major gap between real-world reputation and online presence. Strong foundation, needs amplification.",
    },
    {
        "practice_name": "Bellaire Bay Dental Care",
        "doctor_name": "Dr. Nestor Villarreal, DDS & Dr. Michael Bankes, DDS",
        "specialty": "General & Family Dentistry",
        "address": "8921 Immokalee Rd",
        "city": "Naples",
        "state": "FL",
        "zip": "34120",
        "phone": "(239) 330-4940",
        "email": "",
        "website": "bellairebaydentalcare.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook (426 likes) + Instagram (@bellairebaydc, 129 followers, 105 posts). Serving one of the fastest-growing areas in Naples with minimal social reach.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 31,
        "key_opportunity": "Fast-growing North Naples community with low social following. Local family audience is there — needs targeted content and geo-based paid promotion.",
    },
    {
        "practice_name": "Orangetree Dental Care",
        "doctor_name": "Practice dental team",
        "specialty": "General & Family Dentistry",
        "address": "13600 Immokalee Rd, Unit 102",
        "city": "Naples",
        "state": "FL",
        "zip": "34120",
        "phone": "(239) 234-2515",
        "email": "",
        "website": "orangetreedentalcare.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook (226 likes) + Instagram. Serving the fast-growing Orangetree/Ave Maria corridor with minimal social visibility.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 31,
        "key_opportunity": "Serves rapidly expanding NE Naples area with booming population. Low following in a market with high untapped local audience on social.",
    },
    {
        "practice_name": "Mission Hills Dentistry",
        "doctor_name": "Practice dental team",
        "specialty": "General & Cosmetic Dentistry",
        "address": "7485 Vanderbilt Beach Rd",
        "city": "Naples",
        "state": "FL",
        "zip": "34119",
        "phone": "(239) 776-7626",
        "email": "",
        "website": "missionhillsdentistry.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Website + Facebook + Instagram (88 followers, 87 posts). Very low engagement in an affluent North Naples zip. Posting without reaching the right audience.",
        "opportunity_tier": "MEDIUM",
        "presence_score": 31,
        "key_opportunity": "Located in affluent North Naples (34119) with only 88 IG followers. Affluent demographics = high-value cosmetic dental audience just waiting to be engaged.",
    },

    # ── LOW OPPORTUNITY (well-established) ───────────────────────
    {
        "practice_name": "Gateway of Naples Dental",
        "doctor_name": "Practice dental team",
        "specialty": "General & Family Dentistry",
        "address": "2176 Tamiami Trl N",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 403-7200",
        "email": "",
        "website": "gatewayofnaplesdental.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active website + Facebook + Instagram. Good dual-platform presence for an independent practice.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Established on two platforms. Lower priority unless pitching YouTube, TikTok expansion, or paid social campaigns.",
    },
    {
        "practice_name": "Naples Family Dentist",
        "doctor_name": "Dr. Paul D. Mabe, DDS",
        "specialty": "General & Family Dentistry",
        "address": "877 111th Ave N, Suite 3",
        "city": "Naples",
        "state": "FL",
        "zip": "34108",
        "phone": "(239) 566-7737",
        "email": "",
        "website": "naplesfamilydentist.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook (NaplesFamilyDentist) + Instagram (@naples_family_dentist). Consistently posting on both platforms.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Solid dual-platform presence. Could expand to YouTube/TikTok for patient education content to stand out from competitors.",
    },
    {
        "practice_name": "Naples Dental and Wellness Center",
        "doctor_name": "Dr. Rodion Pinkhasov, DDS",
        "specialty": "Cosmetic & General Dentistry / Wellness",
        "address": "8850 Founders Square Dr, Unit 225",
        "city": "Naples",
        "state": "FL",
        "zip": "34120",
        "phone": "(239) 963-2325",
        "email": "",
        "website": "naplesdentalandwellness.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram (@rodiondental). Wellness-integrated dental practice with a growing social presence.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Wellness + dental is a trending niche. Could expand to YouTube for holistic health content — strong differentiation from typical dental practices.",
    },
    {
        "practice_name": "M&R Dental Family",
        "doctor_name": "Practice dental team",
        "specialty": "General & Family Dentistry (Bilingual EN/ES)",
        "address": "7740 Preserve Ln, Unit 11",
        "city": "Naples",
        "state": "FL",
        "zip": "34119",
        "phone": "(239) 359-6136",
        "email": "",
        "website": "naplesdentistflorida.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram. Bilingual (English/Spanish) family practice in North Naples.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Bilingual practice — Spanish-language social content is hugely underserved in Naples. TikTok and IG Reels in Spanish could dominate that niche.",
    },
    {
        "practice_name": "Dentists of South Naples",
        "doctor_name": "Practice dental team (Smile Generation)",
        "specialty": "General & Family Dentistry",
        "address": "6839 Collier Blvd, Suite 103",
        "city": "Naples",
        "state": "FL",
        "zip": "34114",
        "phone": "(239) 206-1659",
        "email": "",
        "website": "dentistsofsouthnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Smile Generation affiliate. Active website + Facebook + Instagram. National backing provides established marketing infrastructure.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Smile Generation affiliate — national-level marketing support. Not a priority target for independent social media services.",
    },
    {
        "practice_name": "Complete Dental Care of Naples",
        "doctor_name": "Practice dental team",
        "specialty": "General & Cosmetic Dentistry",
        "address": "6360 Pine Ridge Rd, Suite 202",
        "city": "Naples",
        "state": "FL",
        "zip": "34119",
        "phone": "(239) 354-5353",
        "email": "",
        "website": "completedentalcareofnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram. North Naples location with established patient base.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Active on both platforms. Paid social campaigns or TikTok presence for younger patient acquisition would be the next growth lever.",
    },
    {
        "practice_name": "Naples Modern Dentistry",
        "doctor_name": "Practice dental team",
        "specialty": "General & Family Dentistry",
        "address": "7430 Immokalee Rd, Suite 102",
        "city": "Naples",
        "state": "FL",
        "zip": "34119",
        "phone": "(239) 316-3763",
        "email": "",
        "website": "naplesmoderndentistry.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram. 'Modern' branding on dual platforms in North Naples.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "'Modern' branding without TikTok/YouTube is a missed opportunity. Short-form video would align perfectly with their identity.",
    },
    {
        "practice_name": "Top Dental Designs",
        "doctor_name": "Practice dental team",
        "specialty": "Cosmetic & Implant Dentistry",
        "address": "5048 Tamiami Trl N",
        "city": "Naples",
        "state": "FL",
        "zip": "34103",
        "phone": "(239) 262-6364",
        "email": "contact@topdentaldesigns.com",
        "website": "topdentaldesigns.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "Yes",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Website + Facebook + Instagram + LinkedIn. One of the more digitally active independent dental practices in Naples.",
        "opportunity_tier": "LOW",
        "presence_score": 51,
        "key_opportunity": "Already active on 3 platforms. Next natural step is YouTube for cosmetic procedure content and TikTok for procedure reveals.",
    },
    {
        "practice_name": "Specialists in Implant Dentistry",
        "doctor_name": "Dr. Matthew Holtan, DDS",
        "specialty": "Dental Implants / Oral Surgery",
        "address": "12052 Tamiami Trl N",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 593-4915",
        "email": "",
        "website": "specialistsinimplantdentistry.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active website + Facebook + Instagram. Implant specialist with established digital presence.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Implant procedure videos are some of the most watched dental content on YouTube. Adding video would be a strong growth channel.",
    },
    {
        "practice_name": "Pelican Bay Family Dental",
        "doctor_name": "Dr. Shamus Loftus, DDS",
        "specialty": "General & Cosmetic Dentistry",
        "address": "5811 Pelican Bay Blvd, Suite 103",
        "city": "Naples",
        "state": "FL",
        "zip": "34108",
        "phone": "(239) 597-4902",
        "email": "",
        "website": "pelicanbayfamilydental.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram (@pelicanbayfamilydental). Established Pelican Bay area practice with premium clientele.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Pelican Bay is a luxury community. Premium lifestyle content strategy could further elevate the brand and attract high-value cosmetic patients.",
    },
    {
        "practice_name": "Cosmetic & Implant Dentistry of Naples",
        "doctor_name": "Dr. Sullivan, DDS",
        "specialty": "Cosmetic Dentistry / Dental Implants",
        "address": "5390 Park Central Ct",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 597-4944",
        "email": "care@dentistryofnaples.com",
        "website": "dentistryofnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "Yes",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Active on Facebook + Instagram + Twitter/X. Established cosmetic implant specialist with solid multi-platform presence.",
        "opportunity_tier": "LOW",
        "presence_score": 51,
        "key_opportunity": "Active on 3 platforms. YouTube for procedure videos and TikTok for smile reveals would round out the digital presence. Not a priority build-out.",
    },
    {
        "practice_name": "Massa Dental Center",
        "doctor_name": "Dr. James W. Massa, DDS",
        "specialty": "Cosmetic Dentistry / Veneers / TMJ",
        "address": "2220 Venetian Ct, Suite 1",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 597-7333",
        "email": "office@massadental.com",
        "website": "jameswmassa.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram (@massa_dentalcenter). 25-year Naples institution. Established cosmetic dentist with world-class veneer work.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "25-year practice with active social. Luxury veneer/cosmetic content for YouTube could target high-net-worth Naples clientele effectively.",
    },
    {
        "practice_name": "Caring Dentistry of Naples",
        "doctor_name": "Dr. Dianelis Blanco, DDS",
        "specialty": "General & Cosmetic Dentistry",
        "address": "2772 Santa Barbara Blvd, Suite 103",
        "city": "Naples",
        "state": "FL",
        "zip": "34116",
        "phone": "(239) 455-1044",
        "email": "",
        "website": "caringdentistryofnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram (@caringdentistryofnaples, 498 followers, 132 posts). Consistent poster in Golden Gate/Santa Barbara area.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Nearly 500 IG followers with consistent content. Spanish-speaking community nearby is underserved. Bilingual TikTok/YouTube would expand reach significantly.",
    },
    {
        "practice_name": "Gulfside Dental",
        "doctor_name": "Practice dental team",
        "specialty": "General & Cosmetic Dentistry",
        "address": "4680 Cardinal Way, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34112",
        "phone": "(239) 774-3017",
        "email": "gulfsidedentalnaplesfl@gmail.com",
        "website": "gulfsidedentalnaples.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram (@naplesdentist, 508 followers, 1,471 posts). Highest content volume in the Naples dental market.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "1,471 IG posts with only 508 followers — posting without strategy. Engagement optimization and audience growth campaigns needed, not more content.",
    },
    {
        "practice_name": "Fantastic Dental Arts",
        "doctor_name": "Dr. Queanh Phan, DDS",
        "specialty": "General & Cosmetic Dentistry",
        "address": "8855 Immokalee Rd, Suite 10",
        "city": "Naples",
        "state": "FL",
        "zip": "34120",
        "phone": "(239) 348-3079",
        "email": "",
        "website": "fantasticdentalarts.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook (525 likes) + Instagram (@fantasticdentalarts, 272 followers). Solid North Naples presence.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Solid dual-platform presence. Not a priority target. Could benefit from YouTube/TikTok for cosmetic procedure content.",
    },
    {
        "practice_name": "Galdos Dental",
        "doctor_name": "Dr. Hugo Galdos Santalo, DMD",
        "specialty": "General, Cosmetic & Implant Dentistry",
        "address": "12355 Collier Blvd, Suite A",
        "city": "Naples",
        "state": "FL",
        "zip": "34116",
        "phone": "(239) 300-4424",
        "email": "contact@galdosdental.com",
        "website": "galdosdental.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "Yes",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 3,
        "website_quality_notes": "Active on Facebook + Instagram + Twitter/X. Most complete social footprint among independent Golden Gate area dental practices.",
        "opportunity_tier": "LOW",
        "presence_score": 51,
        "key_opportunity": "Already on 3 platforms with active website. Lower priority. YouTube/TikTok for procedure content is the logical next channel.",
    },
    {
        "practice_name": "Naples Dental Studio",
        "doctor_name": "Practice dental team",
        "specialty": "General & Cosmetic Dentistry",
        "address": "730 Goodlette Rd N, Suite 206",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 262-4595",
        "email": "",
        "website": "naplesdentalstudio.com",
        "has_facebook": "Yes",
        "has_instagram": "Yes",
        "has_twitter": "No",
        "has_linkedin": "No",
        "has_youtube": "No",
        "has_tiktok": "No",
        "social_platforms_count": 2,
        "website_quality_notes": "Active on Facebook + Instagram. Downtown Naples cosmetic practice with established digital footprint.",
        "opportunity_tier": "LOW",
        "presence_score": 46,
        "key_opportunity": "Downtown Naples location with active social. Not a priority target. Could benefit from paid campaigns targeting high-income zip codes.",
    },
]


def generate_csv():
    output_file = "naples_dental_low_presence.csv"
    fieldnames = [
        "opportunity_tier",
        "presence_score",
        "practice_name",
        "doctor_name",
        "specialty",
        "address",
        "city",
        "state",
        "zip",
        "phone",
        "email",
        "website",
        "social_platforms_count",
        "has_facebook",
        "has_instagram",
        "has_twitter",
        "has_linkedin",
        "has_youtube",
        "has_tiktok",
        "website_quality_notes",
        "key_opportunity",
    ]

    sorted_practices = sorted(
        PRACTICES,
        key=lambda x: (
            0 if x["opportunity_tier"] == "HIGH" else
            1 if x["opportunity_tier"] == "MEDIUM" else 2,
            x["presence_score"]
        )
    )

    with open(output_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for p in sorted_practices:
            writer.writerow({k: p[k] for k in fieldnames})

    print(f"Written: {output_file}")

    high = sum(1 for p in PRACTICES if p["opportunity_tier"] == "HIGH")
    med  = sum(1 for p in PRACTICES if p["opportunity_tier"] == "MEDIUM")
    low  = sum(1 for p in PRACTICES if p["opportunity_tier"] == "LOW")

    print(f"\nSummary:")
    print(f"  HIGH opportunity (no/minimal presence): {high}")
    print(f"  MEDIUM opportunity (Facebook-only or near-zero social): {med}")
    print(f"  LOW opportunity (well-established): {low}")
    print(f"  Total practices researched: {len(PRACTICES)}")

    print(f"\nHIGH OPPORTUNITY LEADS:")
    for p in sorted_practices:
        if p["opportunity_tier"] == "HIGH":
            print(f"  [{p['presence_score']:2d}] {p['practice_name']} — {p['phone']} — {p['email'] or 'no email found'}")

    print(f"\nMEDIUM OPPORTUNITY LEADS:")
    for p in sorted_practices:
        if p["opportunity_tier"] == "MEDIUM":
            print(f"  [{p['presence_score']:2d}] {p['practice_name']} — {p['phone']} — {p['email'] or 'no email found'}")


if __name__ == "__main__":
    generate_csv()
