"""
Manually researched Naples FL doctor practices with social media & website
presence assessment. Data gathered via WebSearch + WebFetch research (June 2026).

Sources used:
  - NPI Registry (blocked in this environment, used npino.com references)
  - Yelp, Healthgrades, WebMD, US News directories
  - Direct Facebook/Instagram/Twitter presence searches
  - Collier County Medical Society listings
  - Practice websites
"""

import csv

# ------------------------------------------------------------------
# Scoring rubric (lower = bigger marketing opportunity):
#   website present       +15
#   website is modern/SSL +5
#   Facebook present      +8
#   Instagram present     +8
#   Twitter/X present     +5
#   LinkedIn present      +4
#   YouTube/TikTok        +5 each
#   contact form          +3
#   schema/meta quality   +3
# ------------------------------------------------------------------

PRACTICES = [
    # ── HIGH OPPORTUNITY ──────────────────────────────────────────
    {
        "practice_name": "Kathleen Broderick, MD",
        "specialty": "Internal Medicine",
        "address": "700 2nd Ave N",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "N/A – listed on directories only",
        "email": "kathleenbroderick@yahoo.com",
        "website": "",
        "website_notes": "No dedicated practice website found; only 3rd-party directory listings (Healthgrades, WebMD, Vitals, Doximity)",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Zero social media presence detected across all platforms",
        "opportunity_tier": "HIGH",
        "presence_score": 0,
        "notes": "Solo internist; 41 years experience; affiliated with NCH Baker Hospital; fluent English/Spanish; 38+ years in Naples",
    },
    {
        "practice_name": "Naples Family Practice (Dr. Gerald Levens, MD)",
        "specialty": "Family Medicine / Concierge",
        "address": "1175 Creekside Pkwy",
        "city": "Naples",
        "state": "FL",
        "zip": "34108",
        "phone": "(239) 284-4333",
        "email": "geraldlevensmd@gmail.com",
        "website": "naplesfamilypractice.com",
        "website_notes": "Basic website, no social media links visible in search results; appears outdated",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "No social media presence detected across any platform",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "notes": "Membership-based practice since 2007; fewer than 300 patients; personalized care focus; solo practice",
    },
    {
        "practice_name": "Dr. Anthony D'Agostino, MD (Solo Practice)",
        "specialty": "Internal Medicine / Primary Care",
        "address": "1350 9th St N, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 262-6111",
        "email": "office@adagostino.com",
        "website": "adagostino.com",
        "website_notes": "Basic practice website; appears minimal/older design; no social media links found anywhere",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "No social media presence on any platform detected",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "notes": "Solo internist since 1996; 2,500+ active patients; FACP board certified; University of Notre Dame / USF graduate",
    },
    {
        "practice_name": "Integris Physicians (Neagu, FL/Valeriu Neagu, MD)",
        "specialty": "Endocrinology, Allergy & Immunology",
        "address": "1019 Crosspointe Dr, Suite 1",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 799-6950",
        "email": "contact@integrisdoc.com",
        "website": "integrisdoc.com",
        "website_notes": "Informational website only; no social media integration",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "No social media accounts found on any platform",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "notes": "2-physician specialty practice; Drs. Florina Neagu (Allergy/Immunology) and Valeriu R. Neagu (Endocrinology); Mon–Fri 8am–4:30pm",
    },
    {
        "practice_name": "Psychiatry of Naples",
        "specialty": "Psychiatry / Mental Health",
        "address": "365 5th Ave S",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 298-1998",
        "email": "",
        "website": "psychnaples.com",
        "website_notes": "Basic informational website; no social links found in search",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "No social media presence detected; women-owned practice; boutique and private",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "notes": "Women-owned psychiatry practice; offers bespoke private services; in-home/preferred location visits available; medication management + therapy",
    },
    {
        "practice_name": "Naples Independent Physicians (Dr. Jennifer & Louis Foley)",
        "specialty": "Pediatrics / Women's Health",
        "address": "1217 Piper Blvd, Suite 202",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 920-9010",
        "email": "",
        "website": "naplesindependentphysicians.com",
        "website_notes": "Membership-based practice website; basic; no social media links found",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "No social media accounts detected on any platform",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "notes": "Membership-based; pediatrics (Dr. Jennifer Foley) and women's health (Dr. Louis Foley); North Naples; after-hours access",
    },
    {
        "practice_name": "Southwest Florida Women's Group",
        "specialty": "OB/GYN",
        "address": "1890 SW Health Pkwy, Suite 303",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 593-0990",
        "email": "",
        "website": "obgynnaplesflorida.com",
        "website_notes": "Website exists; no social media accounts found in search",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "No dedicated social media accounts detected; all-woman physician team; practice since 2001",
        "opportunity_tier": "HIGH",
        "presence_score": 15,
        "notes": "All-female provider team; board-certified OB/GYNs; serving Collier & Lee counties since 2001; Nextdoor presence only",
    },
    {
        "practice_name": "Diamond Cove Concierge Medicine (Dr. Michelle Becker)",
        "specialty": "Concierge / Primary Care",
        "address": "1890 SW Health Pkwy, Suite 100",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 207-8844",
        "email": "",
        "website": "diamondcovemd.com",
        "website_notes": "Professional website; independent physician-owned; no social media links in any search",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Zero social media presence; relies entirely on word-of-mouth and Yelp/Healthgrades reviews",
        "opportunity_tier": "HIGH",
        "presence_score": 18,
        "notes": "Independent; 150-patient cap; $5,700/yr membership; Dr. Becker in Naples since 2009; Yelp: 21 reviews; Birdeye presence",
    },
    {
        "practice_name": "Seaside Oaks Psychiatry (Dr. Monica Robles)",
        "specialty": "Psychiatry / Mental Health",
        "address": "1045 Crosspointe Dr, Suite 2",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 784-2297",
        "email": "",
        "website": "seasideoakspsychiatry.com",
        "website_notes": "Established website; offers ketamine, TMS, therapy; no Facebook or Instagram",
        "has_facebook": False,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": True,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "LinkedIn only; no Facebook or Instagram presence found",
        "opportunity_tier": "HIGH",
        "presence_score": 19,
        "notes": "Founded 2012 by Dr. Robles; 3 therapists, 4 medical providers, 1 dietitian; ketamine infusion, TMS, medication mgmt, psych testing",
    },

    # ── MEDIUM OPPORTUNITY ────────────────────────────────────────
    {
        "practice_name": "Internal Medicine Partners (IMP Naples)",
        "specialty": "Internal Medicine / Aesthetics / Wellness",
        "address": "1726 Medical Blvd, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 596-8804",
        "email": "",
        "website": "impnaples.com",
        "website_notes": "Professional website with aesthetics/wellness services",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook only (@impnaples); no Instagram or other platforms",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "notes": "Drs. Ralph Rodriguez and Alejandro Blanco; 20+ years experience each; internal medicine + aesthetics",
    },
    {
        "practice_name": "Well-Being Medical Center (Dr. Ricardo Martinez)",
        "specialty": "Internal Medicine / Urgent Care",
        "address": "851 5th Ave N, Suite 102",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 315-7801",
        "email": "",
        "website": "well-beingmedicalcenter.org",
        "website_notes": "Website present; internal medicine and urgent care focus",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook only (@wellbeingmc); 98% recommendation rating with 56 reviews",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "notes": "Dr. Ricardo Martinez (owner/founder); 2 physicians; 5 specialty areas; 98% recommendation rate; metabolic diseases specialist",
    },
    {
        "practice_name": "Physicians Life Centers, LLC",
        "specialty": "Internal Medicine / Concierge",
        "address": "1048 Goodlette Rd N, Suite 101",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 325-6504",
        "email": "",
        "website": "physicianslifecenters.com",
        "website_notes": "Practice website; focuses on mind-body-spirit medicine",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook only (@physicianslifecenters); no Instagram or other platforms detected",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "notes": "Concierge-model internal medicine; holistic/integrative approach; TopOfNaples.com and YellowPages listed",
    },
    {
        "practice_name": "Dr. Socrates Perez, MD",
        "specialty": "Internal Medicine / Primary Care",
        "address": "Naples, FL (contact for address)",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "",
        "email": "",
        "website": "socratesperezmd.com",
        "website_notes": "Has website; accepting new patients",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook page (@DrSocratesPerez) only; 25+ years experience; no Instagram",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "notes": "25+ years internal medicine/primary care in Naples; accepting new patients",
    },
    {
        "practice_name": "Concierge Medical of Naples (Dr. O. Khan, MD)",
        "specialty": "Internal Medicine / Geriatrics",
        "address": "Naples, FL",
        "city": "Naples",
        "state": "FL",
        "zip": "",
        "phone": "",
        "email": "",
        "website": "",
        "website_notes": "No dedicated website found; primary presence is Facebook",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook only (@conciergemedicalofnaples); Fellowship Trained, Board Certified Geriatrician/Internist",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "notes": "Dr. O. Khan, MD FACP; Fellowship-trained geriatrician; concierge practice; no website found – Facebook is primary channel",
    },
    {
        "practice_name": "North Naples Gynecology & Obstetrics (Dr. Dean Hildahl)",
        "specialty": "OB/GYN",
        "address": "1865 Veterans Park Dr, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 206-2780",
        "email": "",
        "website": "northnaplesobgyn.com",
        "website_notes": "Website present; limited content",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook page (limited activity, low following); no Instagram",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "notes": "Dr. Dean Hildahl; obstetrics, menopause, infertility, abnormal pap smears; private practice",
    },
    {
        "practice_name": "Wellness for Women of Naples (Dr. Tracye Zlobl)",
        "specialty": "Gynecology / Menopause",
        "address": "6610 Willow Park Dr, Suite 102",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 262-3100",
        "email": "",
        "website": "wellnessforwomenofnaples.com",
        "website_notes": "Practice website present; gynecology focus",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook only (@Wellness-For-Women); no Instagram; hours: M–Th 8:30am–4pm, Fri 8:30am–noon",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "notes": "Dr. Tracye Zlobl; menopause specialist; bioidentical hormones; pelvic floor; boutique gynecology practice",
    },
    {
        "practice_name": "Meliora Healthcare",
        "specialty": "Gastroenterology / Hepatology / Sleep Medicine",
        "address": "708 Goodlette-Frank Rd, 2nd Floor",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 291-7005",
        "email": "contact@meliorahealthcare.org",
        "website": "meliorahealthcare.com",
        "website_notes": "Multi-specialty practice website; relatively new",
        "has_facebook": False,
        "has_instagram": True,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Instagram only (@meliorahealth) – 88 followers, 271 posts; no Facebook page found",
        "opportunity_tier": "MEDIUM",
        "presence_score": 28,
        "notes": "Private multi-specialty: gastroenterology, hepatology, sleep medicine, pulmonology; Mon–Fri 8am–4pm; newer practice",
    },
    {
        "practice_name": "South Florida Internal Medicine (Dr. John Canterbury)",
        "specialty": "Internal Medicine / Primary Care",
        "address": "680 2nd Ave N, Suite 203",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 330-1382",
        "email": "",
        "website": "sflinternalmedicine.com",
        "website_notes": "Website present; U.S. trained, ABIM-certified physicians",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook page (@DrJohnCanterbury) only; no Instagram or other platforms",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "notes": "Dr. John Canterbury; internal medicine, hypertension, diabetes, preventive care; employment physicals, pre-op exams",
    },
    {
        "practice_name": "EPN Urgent Care",
        "specialty": "Urgent Care / Occupational Medicine",
        "address": "6400 Davis Blvd, Suite 101",
        "city": "Naples",
        "state": "FL",
        "zip": "34104",
        "phone": "",
        "email": "",
        "website": "epncare.com",
        "website_notes": "Website present; since 2004",
        "has_facebook": False,
        "has_instagram": True,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Instagram (@epnurgentcare) – only 7 followers, 10 posts – effectively zero social presence; no Facebook found",
        "opportunity_tier": "MEDIUM",
        "presence_score": 20,
        "notes": "Since 2004; Mon–Fri 8am–7pm, Sat–Sun 8am–2pm; occupational medicine + urgent care; near Countryside Commons plaza",
    },
    {
        "practice_name": "VAVA Clinic (Dr. Vava Nyanudor & Dr. Suzanna Boka)",
        "specialty": "Primary Care / Urgent Care",
        "address": "8855 Immokalee Rd, Unit 3",
        "city": "Naples",
        "state": "FL",
        "zip": "34120",
        "phone": "(239) 331-8520",
        "email": "",
        "website": "vavaclinic.com",
        "website_notes": "Website present; over 20 years in Naples community",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook only (@vavaclinic) – only 52 likes; essentially no social presence",
        "opportunity_tier": "MEDIUM",
        "presence_score": 23,
        "notes": "20+ years serving Naples; Drs. Nyanudor and Boka; affordable urgent + primary care; Yelp: 17 reviews",
    },
    {
        "practice_name": "First Care Clinic Naples",
        "specialty": "Primary Care / Urgent Care",
        "address": "1201 Piper Blvd, Suite 24",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 260-5307",
        "email": "",
        "website": "firstcarenaples.com",
        "website_notes": "Website present; veteran-owned since 2012",
        "has_facebook": False,
        "has_instagram": True,
        "has_twitter": True,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Twitter (@firstcare) and Instagram (@familyfirst_care) – appear minimal; no active Facebook page found",
        "opportunity_tier": "MEDIUM",
        "presence_score": 36,
        "notes": "Veteran-owned; founded 2012; on-site X-ray, labs; same-day appointments; walk-in friendly; North Naples",
    },
    {
        "practice_name": "Collier Urgent Care Centers",
        "specialty": "Urgent Care",
        "address": "3 locations: 1514 Immokalee Rd; 8845 Founders Square Dr; 6360 Pine Ridge Rd",
        "city": "Naples",
        "state": "FL",
        "zip": "34110 / 34120 / 34119",
        "phone": "(239) 593-3232",
        "email": "Info2@collierurgentcare.com",
        "website": "collierurgentcare.com",
        "website_notes": "Multi-location website; walk-in only; no appointment needed",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook only; no Instagram or other platforms; open daily",
        "opportunity_tier": "MEDIUM",
        "presence_score": 33,
        "notes": "3 Naples locations; accepts most insurance including Workers' Comp; 'Naples Most Trusted Medical Clinics'; open daily",
    },

    # ── LOW OPPORTUNITY (well established online) ─────────────────
    {
        "practice_name": "Prime MD of Naples",
        "specialty": "Family Medicine / Geriatrics",
        "address": "Naples, FL 34110",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 481-4111",
        "email": "",
        "website": "primemdofnaples.com",
        "website_notes": "Active website with women's health pages",
        "has_facebook": True,
        "has_instagram": True,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Active Facebook (@Primemdofnaples) + Instagram (@primemdofnaples); regularly updated",
        "opportunity_tier": "LOW",
        "presence_score": 56,
        "notes": "Physician-owned family medicine + geriatrics; women's health; Lee Health affiliate",
    },
    {
        "practice_name": "Advance Medical of Naples",
        "specialty": "Family Medicine / Urgent Care / Occupational",
        "address": "720 Goodlette Rd N",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 206-2525",
        "email": "",
        "website": "advmednaples.com",
        "website_notes": "Established modern website",
        "has_facebook": True,
        "has_instagram": True,
        "has_twitter": True,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook (1,162 likes) + Twitter (@advmednaples) + Instagram; multi-platform active",
        "opportunity_tier": "LOW",
        "presence_score": 66,
        "notes": "Founded 1988 by Dr. Greg Leach; primary, urgent, occupational, wellness; 51 Yelp reviews; well established",
    },
    {
        "practice_name": "Dr. Lorna Fedelem, MD (Custom Wellness Center)",
        "specialty": "Family Medicine / Obesity Medicine / Concierge",
        "address": "9150 Galleria Ct, Suite 200",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "(239) 580-6390",
        "email": "",
        "website": "lornafedelemmd.com",
        "website_notes": "Modern professional website with services pages",
        "has_facebook": True,
        "has_instagram": True,
        "has_twitter": False,
        "has_linkedin": True,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook + Instagram (@lornafedelemmd, 473 followers, 185 posts) + LinkedIn; active multi-platform",
        "opportunity_tier": "LOW",
        "presence_score": 61,
        "notes": "Naples native; FSU COM graduate; board-certified Family Medicine & Obesity Medicine; concierge wellness",
    },
    {
        "practice_name": "Hobdari Family Health (Dr. Lindita Hobdari, MD)",
        "specialty": "Family Medicine (Pediatric to Geriatric)",
        "address": "1855 Veterans Park Dr, Suite 201",
        "city": "Naples",
        "state": "FL",
        "zip": "34109",
        "phone": "",
        "email": "",
        "website": "hobdarihealth.com",
        "website_notes": "Active website; Bonita Springs second location",
        "has_facebook": True,
        "has_instagram": True,
        "has_twitter": True,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook (739 likes) + Instagram (@hobdarihealth, 313 followers, 497 posts) + Twitter (@hobdarihealth – joined 2020 no tweets); active",
        "opportunity_tier": "LOW",
        "presence_score": 61,
        "notes": "Dr. Lindita Hobdari; practice since 2012; America's Most Honored Doctors multi-year; 2 locations",
    },
    {
        "practice_name": "Goodwin Medical Center (Dr. Nancy Goodwin)",
        "specialty": "Emergency Medicine / Internal Medicine / Concierge",
        "address": "12260 Tamiami Trail E, Unit 102",
        "city": "Naples",
        "state": "FL",
        "zip": "34113",
        "phone": "(239) 692-9096",
        "email": "",
        "website": "goodwinmedcenter.com",
        "website_notes": "Modern website with anti-aging/aesthetic services",
        "has_facebook": True,
        "has_instagram": True,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook (@BalanceforHappiness) + Instagram (@goodwinmedcenter, 332 followers); active",
        "opportunity_tier": "LOW",
        "presence_score": 51,
        "notes": "Dr. Nancy Goodwin; double board-certified EM + IM; concierge + aesthetic medicine; founded 2018",
    },
    {
        "practice_name": "Dr. Diane Brzezinski, DO",
        "specialty": "Internal Medicine / Osteopathic",
        "address": "1250 Pine Ridge Rd, Suite 101A",
        "city": "Naples",
        "state": "FL",
        "zip": "34108",
        "phone": "",
        "email": "",
        "website": "drbnaples.com",
        "website_notes": "Professional website with credentials pages; telehealth",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook (@DrBNaples) with 3,899 likes – very strong Facebook presence; voted Best Physician by Naples Daily News readers 9 years",
        "opportunity_tier": "LOW",
        "presence_score": 53,
        "notes": "25+ years experience; FACOI; voted Best Physician Naples Daily News 9 consecutive years; telehealth available",
    },
    {
        "practice_name": "Patel Health (Direct Primary Care)",
        "specialty": "Family Medicine / Direct Primary Care",
        "address": "Naples, FL",
        "city": "Naples",
        "state": "FL",
        "zip": "",
        "phone": "(702) 907-2835",
        "email": "info@patel.health",
        "website": "patel.health",
        "website_notes": "Direct primary care model website",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook (@PatelHealth); DPC model – wholesale pricing on meds/labs/imaging",
        "opportunity_tier": "LOW",
        "presence_score": 43,
        "notes": "DPC model; anytime physician access; wholesale medications, labs, imaging; South Florida premier family practice",
    },
    {
        "practice_name": "Dr. Svetlana Kogan, MD (Custom Longevity, P.A.)",
        "specialty": "Functional / Holistic / Integrative Medicine",
        "address": "720 Fifth Ave S, Suite 209",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 676-6883",
        "email": "",
        "website": "customlongevity.com",
        "website_notes": "Modern integrative medicine website",
        "has_facebook": True,
        "has_instagram": False,
        "has_twitter": False,
        "has_linkedin": True,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook (@Dr.SvetlanaKogan) + LinkedIn; concierge holistic; IFM certified practitioner",
        "opportunity_tier": "LOW",
        "presence_score": 52,
        "notes": "Concierge holistic/functional medicine; IFM Certified; IV vitamins, lifestyle medicine, thyroid, menopause, anxiety; 5th Ave South Naples",
    },
    {
        "practice_name": "Women's Healthcare Physicians of Naples",
        "specialty": "OB/GYN",
        "address": "775 1st Ave N",
        "city": "Naples",
        "state": "FL",
        "zip": "34102",
        "phone": "(239) 217-6513",
        "email": "",
        "website": "whpnaples.com",
        "website_notes": "Active website with 2 locations; patient portal",
        "has_facebook": True,
        "has_instagram": True,
        "has_twitter": False,
        "has_linkedin": False,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook (@WHPNAPLES, 334 likes) + Instagram location page; moderate presence",
        "opportunity_tier": "LOW",
        "presence_score": 56,
        "notes": "2 locations (Naples + North Naples Health Park Blvd); team of board-certified OB/GYNs; online booking",
    },
    {
        "practice_name": "A Woman's Place (OB/GYN)",
        "specialty": "OB/GYN / Mammography",
        "address": "1660 Medical Blvd, Suite 300",
        "city": "Naples",
        "state": "FL",
        "zip": "34110",
        "phone": "(239) 513-0053",
        "email": "",
        "website": "awpnaples.com",
        "website_notes": "Professional website; online booking; 3D mammograms",
        "has_facebook": True,
        "has_instagram": True,
        "has_twitter": False,
        "has_linkedin": True,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook (@awomansplacenaples, 1,092 likes) + Instagram (@awomansplacenaples) + LinkedIn (22 followers); established multi-platform",
        "opportunity_tier": "LOW",
        "presence_score": 66,
        "notes": "Naples premier OB/GYN since 1988; Dr. Jeffrey Heitmann founding; 3D mammograms, MonaLisa Touch; 2 locations",
    },
    {
        "practice_name": "Shoreline Physician Group (Dr. Carlos Portu)",
        "specialty": "Internal Medicine / Primary Care",
        "address": "950 Manatee Rd",
        "city": "Naples",
        "state": "FL",
        "zip": "34114",
        "phone": "(239) 235-7908",
        "email": "drcarlosportu@gmail.com",
        "website": "shorelinephysicians.com",
        "website_notes": "Active modern website; Mon–Fri 8am–6pm",
        "has_facebook": True,
        "has_instagram": True,
        "has_twitter": True,
        "has_linkedin": True,
        "has_youtube": False,
        "has_tiktok": False,
        "social_notes": "Facebook + Instagram (@dr_portu) + Twitter + LinkedIn; established multi-platform; text line available",
        "opportunity_tier": "LOW",
        "presence_score": 76,
        "notes": "Dr. Carlos Portu; established 2018; 15+ years experience; also serves Marco Island; text: (239) 946-9734",
    },
]
